apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-ifaijupc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/backend-tests-go-ifaijupc:azure-8c5858301e12472bdd1337cf1d51762d33a719ba
          name: container-image
